meta-imx: Delete sdio-610 firmware
Issue: LINUXEXEC-34713

sdio-610 has been added in meta-freescale commit deebc27a3abb
("firmware-nxp-wifi: create symbolic links to firmware/mrvl folder"),
so delete it, otherwise it will cause some build errors:

ExpansionError: Failure expanding variable.

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>