tensorflow-lite: fix do_configure failure
Issue: LIN1025-8519

Fix do_configure failure:
error: downloading 'https://gitlab.arm.com/kleidi/kleidiai/-/archive/847ebd19d0192528659b0a0fa2c6057eed674c6a/kleidiai-847ebd19d0192528659b0a0fa2c6057eed674c6a.zip' failed
          status_code: 35
          status_string: "SSL connect error.  If this is due to https certificate verification failure, one may set environment variable CMAKE_TLS_VERIFY=0 to suppress it."

(LOCAL REV: NOT UPSTREAM) -- WRLinux specific

Signed-off-by: Changqing Li <changqing.li@windriver.com>