tensorflow-lite-vx-delegate: set tls version to 1.3 for tensorflow lite
Issue: LIN1025-8558

Fix do_configure failure:
error: downloading 'https://gitlab.arm.com/kleidi/kleidiai/-/archive/847ebd19d0192528659b0a0fa2c6057eed674c6a/kleidiai-847ebd19d0192528659b0a0fa2c6057eed674c6a.zip' failed
          status_code: 35
          status_string: "SSL connect error.  If this is due to https certificate verification failure, one may set environment variable CMAKE_TLS_VERIFY=0 to suppress it."

$ sslscan https://gitlab.arm.com
Version: 2.0.7
OpenSSL 3.0.2 15 Mar 2022

Connected to 13.213.155.27

Testing SSL server gitlab.arm.com on port 443 using SNI name gitlab.arm.com

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   disabled
TLSv1.3   enabled

Only TLSv1.3 is enabled by server, in order to make the host use TLSv1.2
by default work, set tls version to 1.3 for tensorflow lite

Upstream-Status: Pending

Signed-off-by: Changqing Li <changqing.li@windriver.com>