tensorflow-lite-ethosu-delegate: set tls version to 1.3
Issue: LIN1025-8711

Fix do_configure failure:
error: downloading 'https://gitlab.arm.com/kleidi/kleidiai/-/archive/847ebd19d0192528659b0a0fa2c6057eed674c6a/kleidiai-847ebd19d0192528659b0a0fa2c6057eed674c6a.zip' failed
          status_code: 35
          status_string: "SSL connect error.  If this is due to https certificate verification failure, one may set environment variable CMAKE_TLS_VERIFY=0 to suppress it."

$ sslscan https://gitlab.arm.com
Version: 2.1.2
OpenSSL 3.0.13 30 Jan 2024

Connected to 52.220.188.98

Testing SSL server gitlab.arm.com on port 443 using SNI name gitlab.arm.com

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   disabled
TLSv1.3   enabled

Only TLSv1.3 is enabled by server, in order to make the host use TLSv1.2
by default work, set tls version to 1.3 for tensorflow lite

Upstream-Status: Pending

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>