openssl: fix do_patch issue
Issue: LIN1025-7949

Fix following do_patch issue due to upgrade openssl[1], refresh patches:

NOTE: Applying patch '0001-e_devcrypto-add-func-ptr-for-init-do-ctrl.patch' (../layers/meta-imx/meta-imx-bsp/recipes-connectivity/openssl/openssl/0001-e_devcrypto-add-func-ptr-for-init-do-ctrl.patch)
ERROR: Applying patch '0001-e_devcrypto-add-func-ptr-for-init-do-ctrl.patch' on target directory 'TOPDIR/tmp/work/cortexa72-poky-linux/openssl/3.5.5/openssl-3.5.5'
CmdError('quilt --quiltrc TOPDIR/tmp/work/cortexa72-poky-linux/openssl/3.5.5/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-e_devcrypto-add-func-ptr-for-init-do-ctrl.patch

[1] http://lxgit.wrs.com/cgit/oe-core/commit/?h=WRLINUX_10_25_LTS&id=828386b8af065b7f53a6fc74d7781042c2e496be

Signed-off-by: Jinfeng Wang <jinfeng.wang.cn@windriver.com>