meta-imx-bsp/conf/layer.conf: remove the action of installing packagegroup-fsl-optee-imx
Issue: LINUXEXEC-34654

Because the nxp-imx8/9 BSPs install optee related packages in
BSP layer, remove the action of installing packagegroup-fsl-optee-imx
to avoid building error from others BSP. For example, when building
nxp-ls1046 BSP, there is below error:
ERROR: Nothing RPROVIDES 'packagegroup-fsl-optee-imx'
ERROR: Required build target 'wrlinux-image-std' has no buildable providers.
Missing or unbuildable dependency chain was: ['wrlinux-image-std', 'packagegroup-fsl-optee-imx']

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Meng Li <Meng.Li@windriver.com>